cookie:
  expiry_days: 30
  key: "your_random_string_here"
  name: "ai_image_cookie"
credentials:
  usernames:
    admin:
      email: admin@example.com
      first_name: Admin
      last_name: User
      password: "admin123"
      roles: ["admin"]
    testuser:
      email: test@example.com
      first_name: Test
      last_name: User
      password: "user123"
      roles: ["user"]
pre-authorized:
  emails: []